 version: '2'
 services:
   db:
     image: postgres
   web:
     build: .
     command: sh setup_production.sh
     volumes:
       - .:/code
     ports:
       - "8000:8000"
     depends_on:
       - db